/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:controls:710447:
  appc.background(230);
} //_CODE_:controls:710447:

public void numTrucksChanged(GCustomSlider source, GEvent event) { //_CODE_:numTrucksSlider:938548:
  intChanges[0] = numTrucksSlider.getValueI();
} //_CODE_:numTrucksSlider:938548:

public void numEmployeesChanged(GCustomSlider source, GEvent event) { //_CODE_:numEmployees:447170:
  intChanges[1] = numEmployees.getValueI();
} //_CODE_:numEmployees:447170:

public void simSpeedChanged(GCustomSlider source, GEvent event) { //_CODE_:simSpeedSlider:923879:
  simSpeed = roundAny(simSpeedSlider.getValueF(), 2);
} //_CODE_:simSpeedSlider:923879:

public void employeeWageChanged(GCustomSlider source, GEvent event) { //_CODE_:employeeWage:992023:
  floatChanges[0] = roundAny(employeeWage.getValueF(), 2);
} //_CODE_:employeeWage:992023:

public void resetButtonClicked(GButton source, GEvent event) { //_CODE_:resetButton:387224:
  reset();
} //_CODE_:resetButton:387224:

public void pauseButtonClicked(GButton source, GEvent event) { //_CODE_:pauseButton:520075:
  if (isPaused){
    loop();
  }
  else{
    noLoop();
  }
  isPaused = ! isPaused;
} //_CODE_:pauseButton:520075:

public void showTrucksClicked(GCheckbox source, GEvent event) { //_CODE_:showTrucksButton:861363:
  showTrucks = showTrucksButton.isSelected();
} //_CODE_:showTrucksButton:861363:

public void showEmployeesClicked(GCheckbox source, GEvent event) { //_CODE_:showEmployeesButton:733093:
  showEmployees = showEmployeesButton.isSelected();
} //_CODE_:showEmployeesButton:733093:

public void applyChangesClicked(GButton source, GEvent event) { //_CODE_:applyChanges:294084:
  applyChanges();
} //_CODE_:applyChanges:294084:

public void packageRequestSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:packageRequestSpeedSlider:623162:
  intChanges[4] = packageRequestSpeedSlider.getValueI();
} //_CODE_:packageRequestSpeedSlider:623162:

public void numShelvesSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:numShelvesSlider:504992:
  intChanges[3] = numShelvesSlider.getValueI();
} //_CODE_:numShelvesSlider:504992:

public void gasPriceSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:gasPriceSlider:515156:
  floatChanges[1] = roundAny(gasPriceSlider.getValueF(), 2);
} //_CODE_:gasPriceSlider:515156:

public void maxLoadSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:maxLoadSlider:946615:
  intChanges[5] = maxLoadSlider.getValueI();
} //_CODE_:maxLoadSlider:946615:

public void numHousesSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:numHousesSlider:744309:
  intChanges[2] = numHousesSlider.getValueI() * 2;
} //_CODE_:numHousesSlider:744309:

public void detailDropClicked(GDropList source, GEvent event) { //_CODE_:detailDrop:359832:
  detail = detailDrop.getSelectedText();
} //_CODE_:detailDrop:359832:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  controls = GWindow.getWindow(this, "Control Window", 0, 0, 400, 315, JAVA2D);
  controls.noLoop();
  controls.setActionOnClose(G4P.KEEP_OPEN);
  controls.addDrawHandler(this, "win_draw1");
  numTrucksSlider = new GCustomSlider(controls, 8, 60, 100, 44, "blue18px");
  numTrucksSlider.setShowValue(true);
  numTrucksSlider.setLimits(5, 1, 10);
  numTrucksSlider.setNumberFormat(G4P.INTEGER, 0);
  numTrucksSlider.setOpaque(false);
  numTrucksSlider.addEventHandler(this, "numTrucksChanged");
  numEmployees = new GCustomSlider(controls, 8, 125, 100, 44, "blue18px");
  numEmployees.setShowValue(true);
  numEmployees.setLimits(10, 1, 20);
  numEmployees.setNumberFormat(G4P.INTEGER, 0);
  numEmployees.setOpaque(false);
  numEmployees.addEventHandler(this, "numEmployeesChanged");
  simSpeedSlider = new GCustomSlider(controls, 130, 205, 100, 44, "grey_blue");
  simSpeedSlider.setShowValue(true);
  simSpeedSlider.setShowLimits(true);
  simSpeedSlider.setLimits(5.0, 1.0, 50.0);
  simSpeedSlider.setShowTicks(true);
  simSpeedSlider.setNumberFormat(G4P.DECIMAL, 2);
  simSpeedSlider.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  simSpeedSlider.setOpaque(false);
  simSpeedSlider.addEventHandler(this, "simSpeedChanged");
  employeeWage = new GCustomSlider(controls, 250, 60, 100, 44, "purple18px");
  employeeWage.setShowValue(true);
  employeeWage.setLimits(20.0, 1.0, 50.0);
  employeeWage.setNumberFormat(G4P.DECIMAL, 2);
  employeeWage.setOpaque(false);
  employeeWage.addEventHandler(this, "employeeWageChanged");
  resetButton = new GButton(controls, 130, 10, 105, 30);
  resetButton.setText("Reset");
  resetButton.addEventHandler(this, "resetButtonClicked");
  pauseButton = new GButton(controls, 8, 10, 105, 30);
  pauseButton.setText("Pause/Unpause");
  pauseButton.addEventHandler(this, "pauseButtonClicked");
  truckLabel = new GLabel(controls, 18, 41, 80, 20);
  truckLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  truckLabel.setText("Trucks");
  truckLabel.setOpaque(false);
  speedLabel = new GLabel(controls, 125, 186, 112, 20);
  speedLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  speedLabel.setText("Simulation Speed");
  speedLabel.setOpaque(false);
  employeesLabel = new GLabel(controls, 18, 106, 80, 20);
  employeesLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  employeesLabel.setText("Employees");
  employeesLabel.setOpaque(false);
  houseLabel = new GLabel(controls, 18, 165, 80, 20);
  houseLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  houseLabel.setText("Houses");
  houseLabel.setOpaque(false);
  wageLabel = new GLabel(controls, 250, 41, 102, 20);
  wageLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  wageLabel.setText("Employee Wage");
  wageLabel.setOpaque(false);
  showTrucksButton = new GCheckbox(controls, 250, 240, 98, 20);
  showTrucksButton.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showTrucksButton.setText("Show Trucks");
  showTrucksButton.setOpaque(false);
  showTrucksButton.addEventHandler(this, "showTrucksClicked");
  showTrucksButton.setSelected(true);
  showEmployeesButton = new GCheckbox(controls, 250, 270, 120, 20);
  showEmployeesButton.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showEmployeesButton.setText("Show Employees");
  showEmployeesButton.setOpaque(false);
  showEmployeesButton.addEventHandler(this, "showEmployeesClicked");
  showEmployeesButton.setSelected(true);
  applyChanges = new GButton(controls, 250, 10, 105, 30);
  applyChanges.setText("Apply Changes");
  applyChanges.addEventHandler(this, "applyChangesClicked");
  packageRequestSpeed = new GLabel(controls, 130, 43, 103, 34);
  packageRequestSpeed.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  packageRequestSpeed.setText("Package Request Speed");
  packageRequestSpeed.setOpaque(false);
  packageRequestSpeedSlider = new GCustomSlider(controls, 130, 78, 100, 44, "red_yellow18px");
  packageRequestSpeedSlider.setShowValue(true);
  packageRequestSpeedSlider.setLimits(10, 1, 25);
  packageRequestSpeedSlider.setNumberFormat(G4P.INTEGER, 0);
  packageRequestSpeedSlider.setOpaque(false);
  packageRequestSpeedSlider.addEventHandler(this, "packageRequestSliderChanged");
  numShelvesSlider = new GCustomSlider(controls, 8, 252, 100, 44, "blue18px");
  numShelvesSlider.setShowValue(true);
  numShelvesSlider.setLimits(6, 1, 10);
  numShelvesSlider.setNumberFormat(G4P.INTEGER, 0);
  numShelvesSlider.setOpaque(false);
  numShelvesSlider.addEventHandler(this, "numShelvesSliderChanged");
  shelvesLabel = new GLabel(controls, 18, 230, 80, 20);
  shelvesLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  shelvesLabel.setText("Shelves");
  shelvesLabel.setOpaque(false);
  gasPriceSlider = new GCustomSlider(controls, 250, 125, 100, 44, "purple18px");
  gasPriceSlider.setShowValue(true);
  gasPriceSlider.setLimits(1.3, 0.1, 5.0);
  gasPriceSlider.setNumberFormat(G4P.DECIMAL, 2);
  gasPriceSlider.setOpaque(false);
  gasPriceSlider.addEventHandler(this, "gasPriceSliderChanged");
  gasPriceLabel = new GLabel(controls, 260, 106, 80, 20);
  gasPriceLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  gasPriceLabel.setText("Gas Price");
  gasPriceLabel.setOpaque(false);
  maxLoadSlider = new GCustomSlider(controls, 130, 140, 100, 44, "red_yellow18px");
  maxLoadSlider.setShowValue(true);
  maxLoadSlider.setLimits(100, 20, 400);
  maxLoadSlider.setNumberFormat(G4P.INTEGER, 0);
  maxLoadSlider.setOpaque(false);
  maxLoadSlider.addEventHandler(this, "maxLoadSliderChanged");
  maxLoadLabel = new GLabel(controls, 130, 122, 98, 20);
  maxLoadLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  maxLoadLabel.setText("Truck Max Load");
  maxLoadLabel.setOpaque(false);
  numHousesSlider = new GCustomSlider(controls, 8, 186, 100, 44, "blue18px");
  numHousesSlider.setShowValue(true);
  numHousesSlider.setLimits(3, 1, 5);
  numHousesSlider.setNumberFormat(G4P.INTEGER, 0);
  numHousesSlider.setOpaque(false);
  numHousesSlider.addEventHandler(this, "numHousesSliderChanged");
  detailDrop = new GDropList(controls, 250, 205, 98, 104, 3, 10);
  detailDrop.setItems(loadStrings("list_359832"), 3);
  detailDrop.addEventHandler(this, "detailDropClicked");
  detailLabel = new GLabel(controls, 258, 168, 80, 36);
  detailLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  detailLabel.setText("Graphics Quality");
  detailLabel.setOpaque(false);
  controls.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controls;
GCustomSlider numTrucksSlider; 
GCustomSlider numEmployees; 
GCustomSlider simSpeedSlider; 
GCustomSlider employeeWage; 
GButton resetButton; 
GButton pauseButton; 
GLabel truckLabel; 
GLabel speedLabel; 
GLabel employeesLabel; 
GLabel houseLabel; 
GLabel wageLabel; 
GCheckbox showTrucksButton; 
GCheckbox showEmployeesButton; 
GButton applyChanges; 
GLabel packageRequestSpeed; 
GCustomSlider packageRequestSpeedSlider; 
GCustomSlider numShelvesSlider; 
GLabel shelvesLabel; 
GCustomSlider gasPriceSlider; 
GLabel gasPriceLabel; 
GCustomSlider maxLoadSlider; 
GLabel maxLoadLabel; 
GCustomSlider numHousesSlider; 
GDropList detailDrop; 
GLabel detailLabel; 
